Hw 4
EuganeLebedev/FE57-onl-js pull request #4
Opened 2024-02-27 19:08 UTC by EuganeLebedev

2024-03-12 11:41 UTC, NikeLike101 requested changes

2024-03-12 11:41 UTC, NikeLike101 commented on hw_3/static/js/task_1.js
> +let my_variable1 = 'true'
Переменные(да и почти всё) в js  принято называть в camelCase стиле, не ошибка но стоит приучиться)

2024-03-12 11:41 UTC, NikeLike101 commented on hw_3/static/js/task_6.js
> +else {
здесь двойное сообщение если введу от 16 до 18, надо починить

2024-03-12 11:41 UTC, NikeLike101 commented on hw_4/static/src/js/task_9.js
> +    let totalPurchase = PHONE_PRICE;
каждый раз сброс до 2000, видимо знак забыл

2024-03-12 16:17 UTC, EuganeLebedev commented on hw_4/static/src/js/task_9.js
> +    let totalPurchase = PHONE_PRICE;
Это стоимость покупки. Она каждый раз начинается со стоимости телефона. Потом добавляются аксессуары

2024-03-12 16:20 UTC, EuganeLebedev commented on hw_3/static/js/task_6.js
> +else {
Если про это: 
<img width="359" alt="image" src="https://github.com/EuganeLebedev/FE57-onl-js/assets/60517226/d36aadc6-9adf-4c46-bb1a-2ee6e4ebd329">
то тут вроде же было в условии добавить 2е сообщение:
<img width="583" alt="image" src="https://github.com/EuganeLebedev/FE57-onl-js/assets/60517226/9c15c699-b3c9-48e8-a333-00e88f2871f3">

2024-03-14 09:38 UTC, NikeLike101 commented on hw_3/static/js/task_6.js
> +else {
Пожалуй ты прав)

2024-03-14 09:42 UTC, NikeLike101 commented on hw_4/static/src/js/task_9.js
> +    let totalPurchase = PHONE_PRICE;
понял, закупка за конкретную итерацию, слово total смутило, тогда все окей

2024-03-14 09:42 UTC, NikeLike101 commented
Проверено!

2024-03-14 09:42 UTC, closed without merging